import type { FileFormat, Submission, SubmissionView, VersionNode } from '@/types';
import { buildVersionNodes } from '@/services/domain';
type SubmissionDto = { id: string; taskId: string; taskTitle?: string; assignmentId?: string; userId?: string; version?: number; status: Submission['status']; files?: Array<{ id?: string; fileId?: string; name?: string; fileName?: string; format?: string; extension?: string; size?: number; sizeKB?: number; uploadedAt?: string }>; note?: string; submittedAt?: string; reviewedAt?: string; reviewer?: { id?: string; name?: string }; reviewerName?: string; reviewOpinion?: string; reviews?: Submission['reviews']; versions?: Array<{ id?: string; submissionId?: string; version: number; status: Submission['status']; submittedAt: string; reviewedAt?: string; reviewerName?: string; opinion?: string; reviewOpinion?: string; active?: boolean }> };
const formatOf = (raw = ''): FileFormat => { const f = raw.replace(/^\./, '').toUpperCase(); return (['PDF','DOC','DOCX','XLS','XLSX','PPT','PPTX','JPG','PNG'].includes(f) ? f : 'PDF') as FileFormat; };
export function toSubmissionView(dto: SubmissionDto, chain: SubmissionDto[] = [dto]): SubmissionView {
  const submission: Submission = { id: dto.id, taskId: dto.taskId, taskTitle: dto.taskTitle ?? '', assignmentId: dto.assignmentId, userId: dto.userId, version: dto.version ?? 1, status: dto.status,
    files: (dto.files ?? []).map((f) => ({ id: f.fileId ?? f.id ?? '', name: f.fileName ?? f.name ?? '', format: formatOf(f.format ?? f.extension ?? f.name?.split('.').pop()), sizeKB: f.sizeKB ?? Math.ceil((f.size ?? 0) / 1024), uploadedAt: f.uploadedAt ?? '' })),
    note: dto.note ?? '', submittedAt: dto.submittedAt ?? '', reviewedAt: dto.reviewedAt, reviewerName: dto.reviewer?.name ?? dto.reviewerName, reviewOpinion: dto.reviewOpinion, reviews: dto.reviews };
  const versions: VersionNode[] = dto.versions?.map((v) => ({ submissionId: v.submissionId ?? v.id ?? dto.id, version: v.version, status: v.status, submittedAt: v.submittedAt, reviewedAt: v.reviewedAt, reviewerName: v.reviewerName, opinion: v.opinion ?? v.reviewOpinion, active: v.active ?? v.version === submission.version })) ?? buildVersionNodes(chain.map((item) => ({ ...submission, id: item.id, version: item.version ?? 1, status: item.status, submittedAt: item.submittedAt ?? '', reviewedAt: item.reviewedAt, reviewOpinion: item.reviewOpinion, reviewerName: item.reviewer?.name ?? item.reviewerName })));
  const bizStatus = submission.status === 'APPROVED' ? 'APPROVED' : submission.status === 'REJECTED' ? 'REJECTED' : 'PENDING_REVIEW';
  return { ...submission, bizStatus, versions };
}
